### ISSUE TITLE
CoreConfigurationBuilder is missing 

### ISSUE THREAD

**Issue by krissGit** [ACRA/acra#761] opened 2019-09-23 13:10 UTC
Hi I am trying to use the Acra master Branch, CoreConfigurationBuilder class is missing Can you provide the Doc link which will explain me the Setup.

**Comment by F43nd1r** [comment] 2019-09-23 13:12
Duplicate of #677 

Same issue, different class.

**Closed by F43nd1r** 2019-09-23 13:12 UTC
