### ISSUE TITLE
SharePreferences using email (and using database) appear as empty

### ISSUE THREAD

**Issue by Trebia** [ACRA/acra#205] opened 2014-12-11 22:24 UTC
I followed the manual for implementing SharePreferences capture inside ACRA. What I basically did was including the following line in the configuration (is one of the lines of the complete configuration:

  customReportContent = { APP_VERSION, 
                       ANDROID_VERSION,
                       SHARED_PREFERENCES }
  additionalSharedPreferences={"EXTRA_MESSAGE","NOTIF_ACTIVATED"}

However, all the preferences I received in my Cloudant database appear as empty. I made sure that ALL variables are not the default variables, specially on this 2 ones, which are changed earlier in the configuration, I tricked my code just before the message changing intentionally those variables. But, I am still receiving empty values.

I order to double check I included the email option to check what data was written by ACRA, also filling the field empty. The evidences I have: - Report at Clound Ant with SharedPreferences are empty. - The email text introduced by ACRA and offered to the user is also having the field as "empty". - No error output from ACRA in any operation

After investigating during the morning I am blocked and I don't know what else to do.

SDK21 and ACRA4.5.0 using a 2.3 android mobile.

**Comment by timrae** [comment] 2015-01-22 15:39
"EXTRA_MESSAGE" and "NOTIF_ACTIVATED" are values inside your SharedPreferences right? If so, that's not how you use additionalSharedPreferences... It's used to include an entire database... i.e. the input argument you would use in `context.getSharedPreferences()`

**Comment by timrae** [comment] 2015-01-23 21:27
It's possible that the user ended up confused because none of their `SharedPreferences` were being included because of [this bug](https://github.com/ACRA/acra/pull/228). The documentation itself is clear enough IMO, so I recommend closing this issue.

**Comment by william-ferguson-au** [comment] 2015-01-23 22:33
@Trebia could you please post your ACRA config.
Have you specified a value for ```excludeMatchingSharedPreferencesKeys```?

**Comment by william-ferguson-au** [comment] 2015-01-23 22:34
@timrae I don't think that's a bug. But let's discuss that on the PR.

**Comment by william-ferguson-au** [comment] 2015-01-24 01:23
@Trebia when you say "all the preferences I received in my Cloudant database appear as empty":

Does it list preference keys and the keys have a value of "empty"? 
Or do the preference keys show as "null" or "".
Or do you not even see the preference keys?

Can you please post exactly what you see on your server.

Also, what version of ACRA are you using?

**Comment by Trebia** [comment] 2015-01-24 14:48
Hi there! Thanks a lot for taking care of this issue. I will try to answer all your questions one by one.

If I understood well the comments made by @timrae the message field additionalSharedPreferences is used to include a new database. So I should not have used it, however that does not explain why in my  default sharedpreferences all inputs are empty.

@william-ferguson-au :this is my configuration

@ReportsCrashes(
	    formUri = "xxxxxxxxxxx",
	    reportType = org.acra.sender.HttpSender.Type.JSON,
	    httpMethod = org.acra.sender.HttpSender.Method.POST,
	    logcatArguments = { "-t", "300", "ActivityManager:I", "XXXXXX:D", "YYYYYY:D", "*:S" },
	    formUriBasicAuthLogin = "xxxxxxxxx",
	    formUriBasicAuthPassword = "yyyyyyyyyyyy",
	    formKey = "", // This is required for backward compatibility but not used
	    customReportContent = {
	            ReportField.APP_VERSION_CODE,
	            ReportField.APP_VERSION_NAME,
	            ReportField.ANDROID_VERSION,
	            ReportField.PACKAGE_NAME,
	            ReportField.REPORT_ID,
	            ReportField.BUILD,
	            ReportField.STACK_TRACE,
	            ReportField.LOGCAT,
	            ReportField.SHARED_PREFERENCES 
	    },
	    mode = ReportingInteractionMode.SILENT,
	    additionalSharedPreferences={"EXTRA_MESSAGE", "NOTIF_ACTIVATED"}
	)

(notice that I added further information in the ReportField, however nothing else changed)

@william-ferguson-au : no, the field excludeMatchingSharedPreferencesKeys is not included. Actually I only received in the database the shared preferences I include as additionalSharedPreferences.

@william-ferguson-au : this is what I am receiving in my cloudant DB:

	TRUE
NOTIF_ACTIVATED	empty
PROPERTY_REG_ID	empty
default	
acra	
lastVersionNr	51

@william-ferguson-au : after my report several other testing mobiles used it basically:

SDK21 and ACRA4.5.0 using several android versions

@william-ferguson-au :+1: 
@timrae :+1:

**Comment by william-ferguson-au** [comment] 2015-01-24 20:36
OK, I think part of the problem is that your reportType==JSON and the
SharedPreferencesCollector creates a string like:

NOTIF_ACTIVATED=empty
PROPERTY_REG_ID=empty
default.acra.lastVersionNr=51

And at your server end you are splitting that up using dot format.


ᐧ

**Comment by Trebia** [comment] 2015-01-25 12:24
@william-ferguson-au I think problem is not on the server. The fields are empty as well when I use email to send the information.

Do you want me to make any test? change the reportType? Just tell me and I will make any test that can help you all. I have seen as well that there are new versions of ACRA, do you want me to double check with newer versions?

**Comment by william-ferguson-au** [comment] 2015-01-25 22:10
When you say you use email to send the information. How are you doing that?


ᐧ

**Comment by Trebia** [comment] 2015-01-26 23:14
So, basically, keeping the configuration as it is. I add an extra line:


                mailTo = "iloveacra@mydomain.com"

And the fields appear as empty in the mail is created:

EXTRA_MESSAGE=empty

NOTIF_ACTIVATED=empty

I followed the manual which is not declaring explicitly any incompatibility with any other option (it might be, if so I will happily improve the manual)

**Comment by william-ferguson-au** [comment] 2015-01-26 23:19
As @timrae said earlier you are misunderstanding what the ```additionalSharedPreferences``` attribute specifies.

This output:
  EXTRA_MESSAGE=empty
  NOTIF_ACTIVATED=empty
is telling you that you have no preferences defined in the shared preferences file called "EXTRA_MESSAGE" or the shared preferences file called "NOTIF_ACTIVATED".

Can you please post the full output from the email.

**Comment by Trebia** [comment] 2015-01-29 20:56
Basically I am getting this error by email:

APP_VERSION_CODE=myappcode
 APP_VERSION_NAME=myversion
 ANDROID_VERSION=2.3.6
 PACKAGE_NAME=com.mypackage
 REPORT_ID=f3250997-58e5-4f95-9d5c-6c49b98490f0
 BUILD=BOARD=GT-S5830
 BOOTLOADER=unknown
 BRAND=samsung
 CPU_ABI=armeabi
 CPU_ABI2=unknown
 DEVICE=GT-S5830
 DISPLAY=GINGERBREAD.BVKT5
 FINGERPRINT=samsung/GT-S5830/GT-S5830:2.3.6/GINGERBREAD/BVKT5:user/release-keys
 HARDWARE=gt-s5830
 HOST=DELL158
 ID=GINGERBREAD
 MANUFACTURER=samsung
 MODEL=GT-S5830
 PRODUCT=GT-S5830
 RADIO=unknown
 SERIAL=unknown
 TAGS=release-keys
 TIME=1344929617000
 TYPE=user
 UNKNOWN=unknown
 USER=dpi
 VERSION.CODENAME=REL
 VERSION.INCREMENTAL=BVKT5
 VERSION.RELEASE=2.3.6
 VERSION.SDK=10
 VERSION.SDK_INT=10

STACK_TRACE=java.lang.Exception: Report requested by developer
 (here is the exception due to request requested by me)

LOGCAT=--------- beginning of /dev/log/system
 --------- beginning of /dev/log/main
(here is the Logcat)

SHARED_PREFERENCES=EXTRA_MESSAGE=empty

NOTIF_ACTIVATED=empty

default.acra.lastVersionNr=51

**Comment by william-ferguson-au** [comment] 2015-02-01 04:51
This output 
```
SHARED_PREFERENCES=EXTRA_MESSAGE=empty

NOTIF_ACTIVATED=empty

default.acra.lastVersionNr=51
```
is telling you that you have 
* no preferences in your EXTRA_MESSAGE shared preferences file
* no preferences in your NOTIF_ACTIVATED shared preferences file
* You have a single preference "acra.lastVersionNr" in your "default" shared preferences file.

NB shared preferences contains no entries unless and until they are explicitly saved there.
I'm not seeing any problem.

In my app I get the same output as you until I save some values into shared preferences.

**Comment by Trebia** [comment] 2015-02-01 11:23
Ok, I understand. How that variable works, however there is something strange here.

EXTRA_MESSAGE and NOTIF_ACTIVATED are both preferences in my "deafult" preferences file. Why they are not appearing as "default.EXTRA_MESSAGE" like?

Is there anything missing in my configuration? Anything I need to do in my preferences? (I investigated without luck the documentation).

I will update the documentation of ACRA once everything is clearer for me.

**Comment by william-ferguson-au** [comment] 2015-02-01 12:08
But are they preferences that have been *modified and saved* to your
default preferences file?
It doesn't appear so from your output.

It doesn't appear that you have any preferences saved to your default
shared preferences (other than "acra.lastVersionNr")

I'm still not seeing where there any holes in the ACRA doco either.


ᐧ

**Comment by Trebia** [comment] 2015-02-01 13:10
Ok, thanks to your comment I had a hint and I discover the source of the problem: I had a wrong understanding of how SharedPreferences were stored and actually I was having a custom field that I was not including.

To avoid the same problem I had to others I included a note helping others in case they are facing this problem.

Thanks for this. From my perspective this issue needs to be rejected.

**Closed** 2015-02-01 13:10 UTC
