### ISSUE TITLE
Notification - Not posted. PendingIntents attached to actions with remote inputs must be mutable

### ISSUE THREAD

**Issue by zamojski** [ACRA/acra#1190] opened 2023-04-20 20:46 UTC
**Describe the bug**
ACRA Notification plugin on Android 13 doesn't show the notification and fails with below stack trace.
```
2023-04-20 22:37:27.298 10589-10630/info.zamojski.soft.towercollector W/ACRA: Report interaction threw exception, will be ignored.
    java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: 0|info.zamojski.soft.towercollector|666|null|10159 Not posted. PendingIntents attached to actions with remote inputs must be mutable
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at org.acra.interaction.ReportInteractionExecutor.performInteractions(ReportInteractionExecutor.kt:50)
        at org.acra.builder.ReportExecutor.execute(ReportExecutor.kt:134)
        at org.acra.builder.ReportBuilder.build(ReportBuilder.kt:151)
        at org.acra.reporter.ErrorReporterImpl.uncaughtException(ErrorReporterImpl.kt:105)
        at info.zamojski.soft.towercollector.MyApplication$1.uncaughtException(MyApplication.java:112)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
        at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
        at java.lang.Thread.dispatchUncaughtException(Thread.java:2306)
     Caused by: java.lang.IllegalArgumentException: 0|info.zamojski.soft.towercollector|666|null|10159 Not posted. PendingIntents attached to actions with remote inputs must be mutable
        at android.os.Parcel.createExceptionOrNull(Parcel.java:3015)
        at android.os.Parcel.createException(Parcel.java:2995)
        at android.os.Parcel.readException(Parcel.java:2978)
        at android.os.Parcel.readException(Parcel.java:2920)
        at android.app.INotificationManager$Stub$Proxy.enqueueNotificationWithTag(INotificationManager.java:3032)
        at android.app.NotificationManager.notifyAsUser(NotificationManager.java:678)
        at android.app.NotificationManager.notify(NotificationManager.java:628)
        at android.app.NotificationManager.notify(NotificationManager.java:604)
        at org.acra.interaction.NotificationInteraction.performInteraction(NotificationInteraction.kt:100)
        at org.acra.interaction.ReportInteractionExecutor.performInteractions$lambda$2$lambda$1(ReportInteractionExecutor.kt:43)
        at org.acra.interaction.ReportInteractionExecutor.$r8$lambda$XxbE04P1atFd9l_vyYmPLWgTl20(Unknown Source:0)
        at org.acra.interaction.ReportInteractionExecutor$$ExternalSyntheticLambda0.call(Unknown Source:6)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: android.os.RemoteException: Remote stack trace:
        at com.android.server.notification.NotificationManagerService.checkDisqualifyingFeatures(NotificationManagerService.java:6932)
        at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6590)
        at com.android.server.notification.NotificationManagerService.enqueueNotificationInternal(NotificationManagerService.java:6442)
        at com.android.server.notification.NotificationManagerService$10.enqueueNotificationWithTag(NotificationManagerService.java:3467)
        at android.app.INotificationManager$Stub.onTransact(INotificationManager.java:1286)
```

Here's the configuration - [ACRA configuration within the app](https://github.com/zamojski/TowerCollector/blob/master/app/src/main/java/info/zamojski/soft/towercollector/MyApplication.java#L243).

**Expected behavior**
A notification is posted to provide input before sending report.

**Version**
 - Android: 13
 - ACRA 5.9.7

**Comment by F43nd1r** [comment] 2023-04-23 20:11
Sorry, this is probably not the answer you want to see:

The issue here is the remote input for comments. While debugging that feature I hit another bug (https://issuetracker.google.com/issues/159152393), which was closed as "intended behaviour". As a result of this "intended behaviour" (you getting my sarkasm yet, google??) this feature cannot be implemented correctly on API >=29. 

I will be deprecating the comment input in notifications with the next release and not show it on API>=29.

**Closed** 2023-04-23 20:18 UTC
Labels: bug
