### ISSUE TITLE
  java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/internal/util/Predicate;

### ISSUE THREAD

**Issue by dolarbhanderi-meka** [ACRA/acra#811] opened 2020-10-15 12:51 UTC
Class not found exception occurs in version (R)30

ACRA.init(this);

ACRA  give error Failed resolution of: Lcom/android/internal/util/Predicate  when i changed target version 30.

**Comment by F43nd1r** [comment] 2020-10-15 13:57
You're using an old version, update.

**Comment by F43nd1r** [comment] 2020-10-15 13:58
Duplicate of #785

**Closed by F43nd1r** 2020-10-15 13:58 UTC
