### ISSUE TITLE
java.lang.IllegalArgumentException

### ISSUE THREAD

**Issue by DenisZhadan** [ACRA/acra#665] opened 2018-04-22 12:40 UTC
library: ch.acra:acra:4.9.2 
phones: Samsung Galaxy S3 Neo (s3ve3g), 1536MB RAM, Android 4.4  and Sony Xperia™ M4 Aqua Dual (E2333), 2048MB RAM, Android 5.0

on attachBaseContext

// The following line triggers the initialization of ACRA
ACRA.init(this);

Error :
```
java.lang.RuntimeException: 
  at android.app.LoadedApk.makeApplication (LoadedApk.java:516)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4582)
  at android.app.ActivityThread.access$1600 (ActivityThread.java:169)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1337)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:136)
  at android.app.ActivityThread.main (ActivityThread.java:5476)
  at java.lang.reflect.Method.invokeNative (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:515)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1283)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1099)
  at dalvik.system.NativeStart.main (Native Method)
Caused by: java.lang.IllegalArgumentException: 
  at java.lang.Enum.valueOf (Enum.java:198)
  at org.acra.legacy.ReportConverter.legacyLoad (ReportConverter.java:297)
  at org.acra.legacy.ReportConverter.convert (ReportConverter.java:77)
  at org.acra.legacy.LegacyFileHandler.updateToCurrentVersionIfNecessary (LegacyFileHandler.java:51)
  at org.acra.ACRA.init (ACRA.java:236)
  at org.acra.ACRA.init (ACRA.java:173)
  at org.acra.ACRA.init (ACRA.java:157)
  at org.acra.ACRA.init (ACRA.java:140)
```
---------------------
```
java.lang.RuntimeException: 
  at android.app.LoadedApk.makeApplication (LoadedApk.java:581)
  at android.app.ActivityThread.handleBindApplication (ActivityThread.java:4584)
  at android.app.ActivityThread.access$1500 (ActivityThread.java:145)
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1384)
  at android.os.Handler.dispatchMessage (Handler.java:102)
  at android.os.Looper.loop (Looper.java:135)
  at android.app.ActivityThread.main (ActivityThread.java:5319)
  at java.lang.reflect.Method.invoke (Native Method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1016)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:811)
Caused by: java.lang.IllegalArgumentException: 
  at java.lang.Enum.valueOf (Enum.java:200)
  at org.acra.legacy.ReportConverter.legacyLoad (ReportConverter.java:297)
  at org.acra.legacy.ReportConverter.convert (ReportConverter.java:77)
  at org.acra.legacy.LegacyFileHandler.updateToCurrentVersionIfNecessary (LegacyFileHandler.java:51)
  at org.acra.ACRA.init (ACRA.java:236)
  at org.acra.ACRA.init (ACRA.java:173)
  at org.acra.ACRA.init (ACRA.java:157)
  at org.acra.ACRA.init (ACRA.java:140)
```

Any comments?

**Comment by F43nd1r** [comment] 2018-04-22 19:25
I'm fairly certain this is already fixed in newer versions, please try to
reproduce this with either 4.11 or 5.1.3

**Comment by DenisZhadan** [comment] 2018-04-22 19:58
ok, Thanks!

**Comment by F43nd1r** [comment] 2018-04-22 20:04
Closing as duplicate of #551 for now.

**Closed by F43nd1r** 2018-04-22 20:04 UTC
