### ISSUE TITLE
Confirmation toast not showing

### ISSUE THREAD

**Issue by dkijkuit** [ACRA/acra#727] opened 2019-02-01 10:17 UTC
Acra 5.2.1 still fails to show confirmation toast (resReportSendSuccessToast):

```
W/MessageQueue: Handler (android.widget.Toast$TN$1) {38da64a} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (android.widget.Toast$TN$1) {38da64a} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:580)
        at android.os.Handler.enqueueMessage(Handler.java:745)
        at android.os.Handler.sendMessageAtTime(Handler.java:697)
        at android.os.Handler.sendMessageDelayed(Handler.java:667)
        at android.os.Handler.sendMessage(Handler.java:604)
        at android.os.Message.sendToTarget(Message.java:436)
        at android.widget.Toast$TN.hide(Toast.java:464)
        at android.app.ITransientNotification$Stub.onTransact(ITransientNotification.java:58)
        at android.os.Binder.execTransact(Binder.java:752)
```

**Comment by dkijkuit** [comment] 2019-02-02 12:53
Also the 5.3.0-b03 version shows the same stacktrace.

**Comment by dkijkuit** [comment] 2019-02-02 12:54
This is my config:

`@AcraCore(
        buildConfigClass = BuildConfig.class,
        reportFormat = StringFormat.JSON,
        reportContent = {
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.ANDROID_VERSION,
                ReportField.PACKAGE_NAME,
                ReportField.BRAND,
                ReportField.PHONE_MODEL,
                //ReportField.SHARED_PREFERENCES,
                ReportField.AVAILABLE_MEM_SIZE,
                ReportField.DISPLAY,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_COMMENT,
                ReportField.REPORT_ID,
                ReportField.BUILD,
                ReportField.STACK_TRACE
        },
        resReportSendSuccessToast = R.string.crash_dialog_ok_toast
)
@AcraHttpSender(
        uri = "http://xxxxxxxxxxxxxx",
        basicAuthLogin = "xxxxxxxxxxx",
        basicAuthPassword = "xxxxxxxxxx",
        httpMethod = HttpSender.Method.POST
)
@AcraToast(
        resText = R.string.crash_error_toast
)
@AcraDialog(
        resText = R.string.crash_dialog_text,
        resPositiveButtonText = R.string.crash_dialog_ok_button_text,
        resIcon = android.R.drawable.ic_dialog_info, //optional. default is a warning sign
        resTitle = R.string.crash_dialog_title, // optional. default is your application name
        resCommentPrompt = R.string.crash_dialog_comment_prompt, // optional. When defined, adds a user text field input with this text resource as a label
        resTheme = R.style.Base_Theme_AppCompat_Light_Dialog
)`

**Comment by F43nd1r** [comment] 2019-02-07 22:29
There is a small fix in the proximity of this feature in 5.3.0-rc01, so you can try that as well.
Does this happen on all android devices? Or just some android versions/only physical devices/only one manufacturer?

**Comment by dkijkuit** [comment] 2019-02-14 06:29
I only tested the OnePlus 6, not sure if it happens on other devices, will check. I will try the RC2 release and post the results.

**Comment by F43nd1r** [comment] 2019-03-12 01:59
Any news? As I cannot reproduce the issue I can't test it myself, and I do want to wait with 5.3.0 release, if this issue persists.

**Comment by dkijkuit** [comment] 2019-03-12 20:41
This doesn't show the toast and it doesn't post the error to the remote site.

`2019-03-12 21:39:55.229 8501-8501/com.xxxxx:acra E/ACRA: Failed to send crash report for /data/user/0/com.xxxxxxxx/app_ACRA-approved/2019-03-12T21:36:55.836+01:00.stacktrace
    org.acra.sender.ReportSenderException: Policy marked this task as incomplete. ACRA will try to send this report again.
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:123)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:76)
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:63)
        at org.acra.sender.JobSenderService.onStartJob(JobSenderService.java:23)
        at android.app.job.JobService$1.onStartJob(JobService.java:62)
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: org.acra.sender.ReportSenderException: Error while sending JSON report via Http POST
        at org.acra.sender.HttpSender.send(HttpSender.java:137)
        at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:111)
        at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:76) 
        at org.acra.sender.SendingConductor.sendReports(SendingConductor.java:63) 
        at org.acra.sender.JobSenderService.onStartJob(JobSenderService.java:23) 
        at android.app.job.JobService$1.onStartJob(JobService.java:62) 
        at android.app.job.JobServiceEngine$JobHandler.handleMessage(JobServiceEngine.java:108) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6863) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1513)
        at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:117)
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:105)
        at java.net.InetAddress.getAllByName(InetAddress.java:1154)
        at com.android.okhttp.Dns$1.lookup(Dns.java:39)
        at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
        at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
        at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:127)
        at org.acra.http.BaseHttpRequest.writeContent(BaseHttpRequest.java:184)
        at org.acra.http.BaseHttpRequest.send(BaseHttpRequest.java:106)
        at org.acra.sender.HttpSender.sendWithoutAttachments(HttpSender.java:166)
        at org.acra.sender.HttpSender.sendHttpRequests(HttpSender.java:148)
        at org.acra.sender.HttpSender.send(HttpSender.java:132)`

**Comment by F43nd1r** [comment] 2019-03-12 20:49
Are you using rc2? This looks like a duplicate of #730, which was fixed between rc1 and rc2

**Comment by dkijkuit** [comment] 2019-03-12 20:56
Your are correct, RC2 solved the issue, the toast now also shows. Thank you! 👍

**Closed** 2019-03-12 21:01 UTC
