### ISSUE TITLE
 Not allowed to start service Intent in Above android 8.0 device

### ISSUE THREAD

**Issue by Kaleeswaran-Chellaiah** [ACRA/acra#688] opened 2018-08-29 10:31 UTC
The issue occurred android 8.0 above device only.The app crash log details attached below & how to solve? 

USER_COMMENT=null
ANDROID_VERSION=8.0.0
APP_VERSION_NAME=1.0
BRAND=samsung
PHONE_MODEL=SM-G935F
CUSTOM_DATA=
STACK_TRACE=java.lang.RuntimeException: Unable to create application com.app.trueflutter.HowzuApplication: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.app.trueflutter/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{c11b562 u0a283 CEM idle procs:1 seq(0,0,0)}
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6065)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
Caused by: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.app.trueflutter/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{c11b562 u0a283 CEM idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
at android.app.ContextImpl.startService(ContextImpl.java:1484)
at android.content.ContextWrapper.startService(ContextWrapper.java:663)
at org.acra.sender.SenderServiceStarter.startService(SenderServiceStarter.java:43)
at org.acra.util.ApplicationStartupProcessor.sendApprovedReports(ApplicationStartupProcessor.java:75)
at org.acra.ACRA.init(ACRA.java:230)
at org.acra.ACRA.init(ACRA.java:156)
at org.acra.ACRA.init(ACRA.java:139)
at com.app.trueflutter.HowzuApplication.onCreate(HowzuApplication.java:234)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
... 8 more
java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.app.trueflutter/org.acra.sender.SenderService (has extras) }: app is in background uid UidRecord{c11b562 u0a283 CEM idle procs:1 seq(0,0,0)}
at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
at android.app.ContextImpl.startService(ContextImpl.java:1484)
at android.content.ContextWrapper.startService(ContextWrapper.java:663)
at org.acra.sender.SenderServiceStarter.startService(SenderServiceStarter.java:43)
at org.acra.util.ApplicationStartupProcessor.sendApprovedReports(ApplicationStartupProcessor.java:75)
at org.acra.ACRA.init(ACRA.java:230)
at org.acra.ACRA.init(ACRA.java:156)
at org.acra.ACRA.init(ACRA.java:139)
at com.app.trueflutter.HowzuApplication.onCreate(HowzuApplication.java:234)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1125)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6062)
at android.app.ActivityThread.-wrap1(Unknown Source:0)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1764)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.app.ActivityThread.main(ActivityThread.java:6944)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by F43nd1r** [comment] 2018-08-29 17:27
Duplicate of #630 
Use 5.1+ or 4.11 to fix this.

**Closed by F43nd1r** 2018-08-29 17:27 UTC
