### ISSUE TITLE
losing org.acra.config.CoreConfiguration & org.acra.config.SchedulerConfiguration

### ISSUE THREAD

**Issue by SoaringAnecdotalBear** [ACRA/acra#808] opened 2020-09-10 03:01 UTC
why threre is not class CoreConfiguration nor class SchedulerConfiguration in acra\acra-core\src\main\java\org\acra\config  ?but some other classes import them.

**Comment by F43nd1r** [comment] 2020-09-13 22:39
Duplicate of #758

**Closed by F43nd1r** 2020-09-13 22:39 UTC

**Comment by F43nd1r** [comment] 2020-09-13 22:41
Explanation is here: https://github.com/ACRA/acra/issues/677#issuecomment-401548693.
