### ISSUE TITLE
Using acra-core/mail/toast version 5.1.3 with compileSdkVersion 21 - FONT NOT FOUND?

### ISSUE THREAD

**Issue by haamaanaa** [ACRA/acra#671] opened 2018-05-25 09:10 UTC
Hi! I'm trying to integrate ARCA for android app which uses minSdk 21 and I get the following error from my gradle build:

`AGPBI: {"kind":"error","text":"error: resource android:attr/fontStyle not found.","sources":[{"file":"C:\\Users\\name\\.gradle\\caches\\transforms-1\\files-1.1\\support-compat-27.0.2.aar\\5a0b07354063bd013ae6ce4d686a0f29\\res\\values\\values.xml","position":{"startLine":19,"startColumn":4,"startOffset":1245,"endColumn":69,"endOffset":1310}}],"original":"","tool":"AAPT"}`

`AGPBI: {"kind":"error","text":"error: resource android:attr/font not found.","sources":[{"file":"C:\\Users\\name\\.gradle\\caches\\transforms-1\\files-1.1\\support-compat-27.0.2.aar\\5a0b07354063bd013ae6ce4d686a0f29\\res\\values\\values.xml","position":{"startLine":19,"startColumn":4,"startOffset":1245,"endColumn":69,"endOffset":1310}}],"original":"","tool":"AAPT"}`

`AGPBI: {"kind":"error","text":"error: resource android:attr/fontWeight not found.","sources":[{"file":"C:\\Users\\name\\.gradle\\caches\\transforms-1\\files-1.1\\support-compat-27.0.2.aar\\5a0b07354063bd013ae6ce4d686a0f29\\res\\values\\values.xml","position":{"startLine":19,"startColumn":4,"startOffset":1245,"endColumn":69,"endOffset":1310}}],"original":"","tool":"AAPT"}`

build.gradle:
android {
        compileSdkVersion 21
        minSdkVersion 21
        targetSdkVersion 21
}

def acraVersion = '5.1.3'

dependencies {
    implementation "ch.acra:acra-core:$acraVersion"
    implementation "ch.acra:acra-mail:$acraVersion"
    implementation "ch.acra:acra-toast:$acraVersion"
}

If I test with compile/min/target SdkVersions == 27, build works. Is there a way to use latest version of ACRA library with older android SDKs? Or if not possible, which version of ACRA would work with SDK 21?

Also, ch.acra.acra version 4.11 causes same error, but version 4.9.2 does not cause error.

**Comment by F43nd1r** [comment] 2018-05-25 11:53
I guess this is a problem with the use of `implementation "com.android.support:support-compat:27.0.2"` in `5.1.3`. Likely fixed by adding `implementation "com.android.support:support-compat:27.1.1"` or using acra `5.2.0-rc1`.

**Comment by F43nd1r** [comment] 2018-05-25 11:55
Or, on second thought might be caused by too low `compileSdkVersion`. Try setting only `compileSdkVersion` to 27

**Comment by haamaanaa** [comment] 2018-05-27 21:56
problem is that I need to have compileSdk set for 21. As if i set it to 27, TargetSdk must be 27 as well, and I can not have it that high yet.

**Comment by F43nd1r** [comment] 2018-05-27 22:09
In this case you'll have to stay with old acra versions. Newer versions are built for newer android versions

**Comment by haamaanaa** [comment] 2018-05-27 22:40
whihc version would be the one available for SDK 21? and where is that downlodable?

**Comment by F43nd1r** [comment] 2018-05-27 23:17
4.9.2 should work fine. However I recommend that you update your targetsdk soon, as old acra versions have issues on oreo and all future versions

**Comment by F43nd1r** [comment] 2018-05-27 23:20
Also consider raising only compilesdkversion, which should be possible according to this https://stackoverflow.com/a/37843784/4388512

**Comment by haamaanaa** [comment] 2018-05-28 11:57
I tested gradle setup with

    compileSdkVersion 27
    minSdkVersion 21
    targetSdkVersion 21

    def acraVersion = '5.1.3'

And yes compilation & deployment works okay.

**Closed** 2018-05-28 12:59 UTC

**Comment by travisfw** [comment] 2018-06-22 21:02
I'm running into this issue too, but updating compileSdkVersion breaks my code. How can I figure out what acra version I can use with compileSdkVersion 25?

**Comment by travisfw** [comment] 2018-06-22 22:41
#!/bin/bash
    for acrav in 5.2.0 5.1.3 5.1.2 4.11 5.1.1 5.1.0 5.0.2 5.0.1 5.0.0 4.9.2 4.9.1 4.9.0 4.8.5 4.8.4 4.8.3 4.8.2 4.8.1
    do hg revert app/build.gradle
      sed -i "s/acraVersion = '4.9.2'/acraVersion = '$acrav'/" app/build.gradle
      grep -m1 acraVersion app/build.gradle; sleep 1
      ./gradlew clean build && { echo success w v $acrav; break; 
    done

... and that gives me version 5.0.2 for compileSdkVersion 25.
