### ISSUE TITLE
Showing Kotlin Version Error When compilin a release apk

### ISSUE THREAD

**Issue by Mokardder** [ACRA/acra#1366] opened 2024-07-22 07:47 UTC
C:/Users/iammo/AndroidStudioProjects/XREntry/.gradle/caches/transforms-3/2490d200085c57ad33ebd6d6a2116214/transformed/jetified-acra-http-5.11.2/jars/classes.jar!/META-INF/acra-http_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.9.0, expected version is 1.7.1.

**Comment by F43nd1r** [comment] 2024-07-22 09:58
Duplicate of #1267

**Closed by F43nd1r** 2024-07-22 09:58 UTC
