### ISSUE TITLE
ACRA adds android:maxSdkVersion=25 to WAKE_LOCK permission which causes crash on Android 8

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#666] opened 2018-04-30 09:14 UTC
As per subject ACRA adds android:maxSdkVersion=25 to WAKE_LOCK permission which causes crash on Android 8

**Comment by F43nd1r** [comment] 2018-04-30 09:26
Duplicate of #651

**Closed** 2018-04-30 09:26 UTC
