### ISSUE TITLE
USER_COMMENT missing from CrashReportData causing NPE

### ISSUE THREAD

**Issue by szijpeter** [ACRA/acra#587] opened 2017-06-13 11:31 UTC
ACRA fails to send reports, due to a missing field from the crash report.
My config: 

```
@ReportsCrashes(formUri = "***",
                mode = ReportingInteractionMode.TOAST,
                resToastText = R.string.crash_toast_text)
```

sending the crash report:
```
 ACRA.getErrorReporter().clearCustomData();
 ACRA.getErrorReporter().putCustomData(EXCEPTION_LEVEL, getLogLevelName(logLevel));
 ACRA.getErrorReporter().putCustomData(EXCEPTION_TAG, tag);
 ACRA.getErrorReporter().putCustomData(EXCEPTION_MESSAGE, message);
 ACRA.getErrorReporter().handleException(error);
```

the exception:
```
E/ACRA: Failed to send crash reports for /data/user/0/com.neti.netiphone/app_ACRA-approved/2017-06-13T13:24:39.660+02:00-IS_SILENT.stacktrace
                                                               java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] org.acra.model.Element.flatten()' on a null object reference
                                                                   at org.acra.sender.HttpSender.remap(HttpSender.java:254)
                                                                   at org.acra.sender.HttpSender.send(HttpSender.java:221)
                                                                   at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:107)
                                                                   at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:74)
                                                                   at org.acra.sender.SenderService.onHandleIntent(SenderService.java:74)
                                                                   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                   at android.os.Looper.loop(Looper.java:148)
                                                                   at android.os.HandlerThread.run(HandlerThread.java:61)
```

I have debugged, that the config.getReportFields() contains the USER_COMMENT (although I have not set it manually), but the report does not, hence the unhandled exception.

Workaround is initing ARCA with a config that disabled the USER_COMMENT field, like this:
`ACRA.init(this, new ConfigurationBuilder(this).setReportField(ReportField.USER_COMMENT, false), true);`

Using version 4.9.2.

Am I doing anything wrong, or is this a bug? :)

**Comment by F43nd1r** [comment] 2017-06-13 11:48
Duplicate of #541 - closing

**Closed by F43nd1r** 2017-06-13 11:48 UTC

**Comment by F43nd1r** [comment] 2017-06-13 15:06
As this seems to be a common issue, I've released a version under my domain (I can't upload to ch.acra). http://search.maven.org/#artifactdetails%7Ccom.faendir%7Cacra%7C4.10.0%7Caar
