### ISSUE TITLE
mailTo annotation not working

### ISSUE THREAD

**Issue by mattcoz** [ACRA/acra#507] opened 2016-08-31 21:35 UTC
I have this annotation set in my Application class:

@ReportsCrashes(mailTo = "mattcoz@gmail.com",
                            mode = ReportingInteractionMode.TOAST,
                            resToastText = R.string.crash_toast_text)

But it does not attempt to send an email. The toast message displays though.

08-31 16:28:53.042: I/ACRA(27394): ACRA is enabled for com.cacorp.inventory, initializing...
08-31 16:29:59.707: E/ACRA(27394): ACRA caught a RuntimeException for com.cacorp.inventory

**Comment by william-ferguson-au** [comment] 2016-08-31 23:04
Post more of your log.

**Comment by F43nd1r** [comment] 2016-08-31 23:09
Probably a duplicate of #490. We really need to promote the info that Acra will not work as a jar.

**Comment by mattcoz** [comment] 2016-08-31 23:54
Yes, I'm using it as a jar. If it's not going to work then it should not be put up for download.

**Comment by william-ferguson-au** [comment] 2016-08-31 23:59
Happy to accept your pull request for that @mattcoz 

The documentation clearly says that ACRA has been packaged as an AAR.

**Closed by william-ferguson-au** 2016-08-31 23:59 UTC
