### ISSUE TITLE
Email client started instead of notification

### ISSUE THREAD

**Issue by NLLAPPS** [ACRA/acra#1084] opened 2022-06-22 12:35 UTC
Just noticed that below config does not create notification but starts email client as soon as crash happens.  Not sure when this behaviour has changed but my config was same for years.

What am I missing?

initAcra {
                buildConfigClass = BuildConfig::class.java
                reportFormat = StringFormat.KEY_VALUE_LIST
                reportContent = listOf(
                    ReportField.USER_COMMENT,
                    ReportField.PACKAGE_NAME,
                    ReportField.APP_VERSION_NAME,
                    ReportField.ANDROID_VERSION,
                    ReportField.BRAND,
                    ReportField.PHONE_MODEL,
                    ReportField.PRODUCT,
                    ReportField.USER_APP_START_DATE,
                    ReportField.USER_CRASH_DATE,
                    ReportField.THREAD_DETAILS,
                    ReportField.STACK_TRACE,
                    ReportField.LOGCAT
                )
                notification {
                    enabled = true
                    title = getString(AppResources.string.crash_notif_title)
                    text = getString(AppResources.string.crash_dialog_text)
                    channelName = getString(AppResources.string.app_crash_notification_channel)
                    sendButtonText = getString(AppResources.string.send)
                    discardButtonText = getString(AppResources.string.cancel)
                    sendOnClick = true
                    resDiscardButtonIcon = AppResources.drawable.crash_log_discard
                    resSendButtonIcon = AppResources.drawable.crash_log_send
                }
                mailSender {
                    enabled = true
                    mailTo = StoreConfigImpl.getStoreContactEmail()
                    reportAsFile = false
                }
            }

**Comment by NLLAPPS** [comment] 2022-06-22 12:58
Atatching ACR debug logs just in case

2022-06-22 13:55:08.657 14464-14464 ACRA                    com.test                           D  Building report
2022-06-22 13:55:08.662 14464-14464 ACRA                    com.test                           D  Starting collectors with priority FIRST
2022-06-22 13:55:08.665 14464-14572 ACRA                    com.test                           D  Calling collector org.acra.collector.DropBoxCollector
2022-06-22 13:55:08.665 14464-14572 ACRA                    com.test                           D  Collector org.acra.collector.DropBoxCollector completed
2022-06-22 13:55:08.666 14464-14574 ACRA                    com.test                           D  Calling collector org.acra.collector.StacktraceCollector
2022-06-22 13:55:08.668 14464-14573 ACRA                    com.test                           D  Calling collector org.acra.collector.LogCatCollector
2022-06-22 13:55:08.670 14464-14574 ACRA                    com.test                           D  Collector org.acra.collector.StacktraceCollector completed
2022-06-22 13:55:08.673 14464-14573 ACRA                    com.test                           D  Retrieving logcat output (buffer:default)...
2022-06-22 13:55:08.684 14464-14573 ACRA                    com.test                           D  Collector org.acra.collector.LogCatCollector completed
2022-06-22 13:55:08.684 14464-14464 ACRA                    com.test                           D  Finished collectors with priority FIRST
2022-06-22 13:55:08.686 14464-14464 ACRA                    com.test                           D  Starting collectors with priority NORMAL
2022-06-22 13:55:08.687 14464-14572 ACRA                    com.test                           D  Calling collector org.acra.collector.DeviceFeaturesCollector
2022-06-22 13:55:08.687 14464-14572 ACRA                    com.test                           D  Collector org.acra.collector.DeviceFeaturesCollector completed
2022-06-22 13:55:08.688 14464-14574 ACRA                    com.test                           D  Calling collector org.acra.collector.ConfigurationCollector
2022-06-22 13:55:08.688 14464-14574 ACRA                    com.test                           D  Collector org.acra.collector.ConfigurationCollector completed
2022-06-22 13:55:08.689 14464-14572 ACRA                    com.test                           D  Calling collector org.acra.collector.MemoryInfoCollector
2022-06-22 13:55:08.689 14464-14572 ACRA                    com.test                           D  Collector org.acra.collector.MemoryInfoCollector completed
2022-06-22 13:55:08.690 14464-14574 ACRA                    com.test                           D  Calling collector org.acra.collector.DisplayManagerCollector
2022-06-22 13:55:08.690 14464-14574 ACRA                    com.test                           D  Collector org.acra.collector.DisplayManagerCollector completed
2022-06-22 13:55:08.690 14464-14572 ACRA                    com.test                           D  Calling collector org.acra.collector.ReflectionCollector
2022-06-22 13:55:08.690 14464-14572 ACRA                    com.test                           D  Collector org.acra.collector.ReflectionCollector completed
2022-06-22 13:55:08.693 14464-14574 ACRA                    com.test                           D  Calling collector org.acra.collector.SharedPreferencesCollector
2022-06-22 13:55:08.693 14464-14574 ACRA                    com.test                           D  Collector org.acra.collector.SharedPreferencesCollector completed
2022-06-22 13:55:08.696 14464-14573 ACRA                    com.test                           D  Calling collector org.acra.collector.CustomDataCollector
2022-06-22 13:55:08.696 14464-14573 ACRA                    com.test                           D  Collector org.acra.collector.CustomDataCollector completed
2022-06-22 13:55:08.699 14464-14581 ACRA                    com.test                           D  Calling collector org.acra.collector.SimpleValuesCollector
2022-06-22 13:55:08.699 14464-14580 ACRA                    com.test                           D  Calling collector org.acra.collector.SettingsCollector
2022-06-22 13:55:08.701 14464-14580 ACRA                    com.test                           D  Collector org.acra.collector.SettingsCollector completed
2022-06-22 13:55:08.702 14464-14579 ACRA                    com.test                           D  Calling collector org.acra.collector.PackageManagerCollector
2022-06-22 13:55:08.702 14464-14578 ACRA                    com.test                           D  Calling collector org.acra.collector.DeviceIdCollector
2022-06-22 13:55:08.703 14464-14578 ACRA                    com.test                           D  Collector org.acra.collector.DeviceIdCollector completed
2022-06-22 13:55:08.703 14464-14582 ACRA                    com.test                           D  Calling collector org.acra.collector.TimeCollector
2022-06-22 13:55:08.703 14464-14581 ACRA                    com.test                           D  Collector org.acra.collector.SimpleValuesCollector completed
2022-06-22 13:55:08.704 14464-14579 ACRA                    com.test                           D  Collector org.acra.collector.PackageManagerCollector completed
2022-06-22 13:55:08.705 14464-14582 ACRA                    com.test                           D  Collector org.acra.collector.TimeCollector completed
2022-06-22 13:55:08.706 14464-14464 ACRA                    com.test                           D  Finished collectors with priority NORMAL
2022-06-22 13:55:08.706 14464-14464 ACRA                    com.test                           D  Starting collectors with priority LATE
2022-06-22 13:55:08.707 14464-14579 ACRA                    com.test                           D  Calling collector org.acra.collector.MediaCodecListCollector
2022-06-22 13:55:08.708 14464-14579 ACRA                    com.test                           D  Collector org.acra.collector.MediaCodecListCollector completed
2022-06-22 13:55:08.710 14464-14582 ACRA                    com.test                           D  Calling collector org.acra.collector.LogFileCollector
2022-06-22 13:55:08.710 14464-14582 ACRA                    com.test                           D  Collector org.acra.collector.LogFileCollector completed
2022-06-22 13:55:08.713 14464-14581 ACRA                    com.test                           D  Calling collector org.acra.collector.ThreadCollector
2022-06-22 13:55:08.714 14464-14581 ACRA                    com.test                           D  Collector org.acra.collector.ThreadCollector completed
2022-06-22 13:55:08.715 14464-14464 ACRA                    com.test                           D  Finished collectors with priority LATE
2022-06-22 13:55:08.715 14464-14464 ACRA                    com.test                           D  Finishing activities prior to killing the Process
2022-06-22 13:55:08.718 14464-14464 ACRA                    com.test                           D  Finished class com.test.ui.MainActivity
2022-06-22 13:55:08.742 14464-14464 ACRA                    com.test                           D  Finished class com.test.ui.settings.SettingsActivity
2022-06-22 13:55:08.742 14464-14464 ACRA                    com.test                           D  Writing crash report file /data/user/0/com.test/app_ACRA-unapproved/2022-06-22T13:55:08.704+01:00.stacktrace
2022-06-22 13:55:08.750 14464-14464 ACRA                    com.test                           D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.interaction.ReportInteraction]
2022-06-22 13:55:08.754 14464-14464 ACRA                    com.test                           D  Checking plugin Configurations : [org.acra.config.NotificationConfiguration@a7490f3] for class : class org.acra.config.NotificationConfiguration
2022-06-22 13:55:08.755 14464-14464 ACRA                    com.test                           D  Checking plugin Configuration : org.acra.config.NotificationConfiguration@a7490f3 against plugin class : class org.acra.config.NotificationConfiguration
2022-06-22 13:55:08.755 14464-14464 ACRA                    com.test                           D  Loaded ReportInteraction of type org.acra.interaction.NotificationInteraction
2022-06-22 13:55:08.766 14464-14584 ACRA                    com.test                           D  Calling ReportInteraction of class org.acra.interaction.NotificationInteraction
2022-06-22 13:55:08.767 14464-14584 ACRA                    com.test                           D  Checking plugin Configurations : [org.acra.config.NotificationConfiguration@a7490f3] for class : class org.acra.config.NotificationConfiguration
2022-06-22 13:55:08.767 14464-14584 ACRA                    com.test                           D  Checking plugin Configuration : org.acra.config.NotificationConfiguration@a7490f3 against plugin class : class org.acra.config.NotificationConfiguration
2022-06-22 13:55:08.774 14464-14464 ACRA                    com.test                           D  Mark 2022-06-22T13:55:08.704+01:00.stacktrace as approved.
2022-06-22 13:55:08.774 14464-14464 ACRA                    com.test                           D  Schedule report sending
2022-06-22 13:55:08.776 14464-14464 ACRA                    com.test                           D  Using PluginLoader to find ReportSender factories
2022-06-22 13:55:08.776 14464-14464 ACRA                    com.test                           D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2022-06-22 13:55:08.779 14464-14464 ACRA                    com.test                           D  Checking plugin Configurations : [org.acra.config.NotificationConfiguration@a7490f3] for class : class org.acra.config.MailSenderConfiguration
2022-06-22 13:55:08.780 14464-14464 ACRA                    com.test                           D  Checking plugin Configuration : org.acra.config.NotificationConfiguration@a7490f3 against plugin class : class org.acra.config.MailSenderConfiguration
2022-06-22 13:55:08.780 14464-14464 ACRA                    com.test                           D  Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2022-06-22 13:55:08.780 14464-14464 ACRA                    com.test                           D  reportSenderFactories : []
2022-06-22 13:55:08.780 14464-14464 ACRA                    com.test                           D  Using PluginLoader to find ReportSender factories
2022-06-22 13:55:08.780 14464-14464 ACRA                    com.test                           D  ServicePluginLoader loading services from ServiceLoader : java.util.ServiceLoader[org.acra.sender.ReportSenderFactory]
2022-06-22 13:55:08.788 14464-14464 ACRA                    com.test                           D  Checking plugin Configurations : [org.acra.config.NotificationConfiguration@a7490f3] for class : class org.acra.config.MailSenderConfiguration
2022-06-22 13:55:08.788 14464-14464 ACRA                    com.test                           D  Checking plugin Configuration : org.acra.config.NotificationConfiguration@a7490f3 against plugin class : class org.acra.config.MailSenderConfiguration
2022-06-22 13:55:08.788 14464-14464 ACRA                    com.test                           D  Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory
2022-06-22 13:55:08.788 14464-14464 ACRA                    com.test                           D  reportSenderFactories : []
2022-06-22 13:55:08.797 14464-14464 ACRA                    com.test                           D  Wait for Interactions + worker ended. Kill Application ? true

**Comment by F43nd1r** [comment] 2022-06-24 08:10
The logs don't match your description, `Ignoring disabled ReportSenderFactory of type EmailIntentSenderFactory` means no email client can be opened. Also please state your ACRA and android version

**Comment by NLLAPPS** [comment] 2022-06-24 09:53
Here is a POC for it. Try on API level 32/33 emulato
[MyApplication.zip](https://github.com/ACRA/acra/files/8975198/MyApplication.zip)
r

**Comment by F43nd1r** [comment] 2022-07-01 22:20
Okay so this only happens on API 32+. ACRA has not been updated for 31+ yet. I'll have a look what needs changing when I have more time.

**Comment by NLLAPPS** [comment] 2022-07-01 22:36
> Okay so this only happens on API 32+.
I have not tested below 32. Have you? I can if you like

**Comment by F43nd1r** [comment] 2022-07-01 22:57
I checked on API 30 and 33, where 30 worked as intended and 33 as you described. If you want to investigate which API introduced the breaking change, search between those two

**Comment by henrichg** [comment] 2022-07-18 12:27
Maybe problem in API 33 is with this: "Privacy - Runtime permission for notifications"
Link: https://developer.android.com/about/versions/13/behavior-changes-all

**Comment by NLLAPPS** [comment] 2022-07-18 13:16
"In API 33, when notiifcatons are enabled in device Settings, notification is also displayed. Tested in Pixel 6, Android 13 latest beta."

My app is phone dialer, it is excluded from notification permissions (as in, it has notification permission). 
Target SDK might be significant and mine and sample app I have uploaded are targeting 33

**Comment by F43nd1r** [comment] 2022-07-30 18:33
Fixed in [c9283f5](https://github.com/ACRA/acra/commit/c9283f51c7c86b36cd82b16da42c6a90f87bdafe)

**Closed by F43nd1r** 2022-07-30 18:33 UTC
Labels: bug
