### ISSUE TITLE
FCM don't receive token

### ISSUE THREAD

**Issue by zloyreznic** [ACRA/acra#662] opened 2018-04-18 07:46 UTC
Firebase Cloud Message with acra

implementation 'ch.acra:acra-core:5.1.1'

Example https://github.com/firebase/quickstart-android/tree/master/messaging
Add to project dependencies acra and don't receive token on Android 8(API 26)

**Comment by F43nd1r** [comment] 2018-04-18 07:51
Which token are you talking about?

**Comment by zloyreznic** [comment] 2018-04-18 07:56
String token = FirebaseInstanceId.getInstance().getToken();

**Comment by F43nd1r** [comment] 2018-04-18 08:06
I don't see how acra could have anything to do with that

**Comment by NLLAPPS** [comment] 2018-04-30 09:11
I had same issue, clearing build cache helped. I am not sure it is related though

**Comment by F43nd1r** [comment] 2018-06-08 20:50
Assuming build cache cleaning is the solution here - closing

**Comment by zeallat** [comment] 2018-07-13 01:45
I had same issue, and clearing build cache not helped.

**Comment by brian98point6** [comment] 2018-08-30 18:31
We have this issue too and see null firebase tokens for our end-users.

This seemed to have been caused by our upgrade from acra:4.11 to acra-http:5.1.3. I demonstrated this to myself by reverting back to acra:4.11 and getting the firebase token successfully. My colleague tried removing acra altogether from the app and that also seems to restore firebase token receiving.

Our repro specifically is:
1. Uninstall the app if it is there (this seems to be an important step)
2. Install and run the app with Acra 5.1.3
3. Observe the following:
  i. FirebaseInstanceId.getInstance().getToken() is null even well after app startup
  ii. Overridden FirebaseInstanceIdService.onTokenRefresh() is not invoked (if registered in manifest)
  iii. Overridden FirebaseMessagingService.onNewToken() is not invoked (if registered in manifest)

As others mentioned, this seems to affect only Android 8.0+.

@F43nd1r : Since this seems to be triggered by acra 5, I think that justifies keeping this bug report open. What do you think?

In the meantime, I'll try to find additional troubleshooting info.

**Comment by brian98point6** [comment] 2018-08-30 20:05
I narrowed it down to acra-http:5.1.1:

* acra:4.11: firebase token received
* acra-http:5.0.0: firebase token received
* acra-http:5.1.0: firebase token received
* acra-http:5.1.1: **null firebase token**
* acra-http:5.1.3: **null firebase token**

**Comment by F43nd1r** [comment] 2018-08-30 21:59
Thanks for investigating @brian98point6 . I've checked all the commits between .0 and .1, and the only commit which might have side effects seems to be 61d3485324356728c82793af7986ffd23bec0690.
I won't be able to check this out in the next few days. 
If you or someone else wants to bring this forward, try to revert each change in that commit individually and test if the issue is fixed.

**Comment by zloyreznic** [comment] 2018-08-31 07:05
Maybe this help? 
<uses-permission
	  android:name="android.permission.WAKE_LOCK"
	  tools:remove="android:maxSdkVersion" />
Try no get FCM Token with new SDK
Kotlin 
```
FirebaseInstanceId.getInstance().instanceId.addOnSuccessListener { result ->
                val fcmToken = result.token
}
```

**Comment by NLLAPPS** [comment] 2018-08-31 07:52
It could be wakelock permission

**Comment by F43nd1r** [comment] 2018-09-03 23:32
It is the wakelock permission. I'm removing the maxSdkVersion, as it seems to do more harm than good.

**Comment by F43nd1r** [comment] 2018-09-03 23:34
Please confirm that #690 solves the issue. @brian98point6 @zloyreznic @NLLAPPS @zeallat

**Comment by F43nd1r** [comment] 2018-09-04 21:18
@brian98point6 yes, this whole problem is caused by bad behaviour of the manifest merger: it just merges the xml tags, preserving the maxsdk attribute from acras tag (as there is no conflict because the attribute is not present on firebases tag). 

This is a general problem, not only for firebase (which is why it was already noted in the [wiki](https://github.com/ACRA/acra/wiki/Troubleshooting-Guide#wake_lock)).
Because the problem is hard to notice (as proven in this issue) and the benefit of having the maxsdk tag is miniscule, I've decided to to remove the maxsdk tag. Users who do not need wake_lock permissions may add it themselves.

**Closed** 2018-09-05 01:36 UTC
