### ISSUE TITLE
java.lang.RuntimeException: Unable to create application com.naoow.NaoowApplication: java.lang.IllegalArgumentException: {"APP_VERSION_NAME" is not a constant in org.acra.ReportField

### ISSUE THREAD

**Issue by krupinder955** [ACRA/acra#642] opened 2018-02-15 06:02 UTC
java.lang.RuntimeException: Unable to create application com.naoow.NaoowApplication: java.lang.IllegalArgumentException: {"APP_VERSION_NAME" is not a constant in org.acra.ReportField
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4443)
at android.app.ActivityThread.access$1500(ActivityThread.java:141)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5113)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:609)
at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.IllegalArgumentException: {"APP_VERSION_NAME" is not a constant in org.acra.ReportField
at java.lang.Enum.valueOf(Enum.java:198)
at org.acra.legacy.ReportConverter.legacyLoad(ReportConverter.java:297)
at org.acra.legacy.ReportConverter.convert(ReportConverter.java:77)
at org.acra.legacy.LegacyFileHandler.updateToCurrentVersionIfNecessary(LegacyFileHandler.java:51)
at org.acra.ACRA.init(ACRA.java:236)
at org.acra.ACRA.init(ACRA.java:173)
at org.acra.ACRA.init(ACRA.java:157)
at org.acra.ACRA.init(ACRA.java:140)
at com.naoow.NaoowApplication.onCreate(NaoowApplication.java:37)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4440)

**Comment by F43nd1r** [comment] 2018-02-15 21:56
Duplicate of #551, which was fixed in 4.9.3
Please reopen if you are using 4.9.3 or later.

**Closed by F43nd1r** 2018-02-15 21:56 UTC

**Comment by krupinder955** [comment] 2018-02-17 18:06
Currently, i am using 4.9.2 version and getting this Exception.
When i try with this dependency compile 'ch.acra:acra:4.9.2' , i am unable to compile the project.

**Comment by F43nd1r** [comment] 2018-02-17 18:12
Use `compile 'com.faendir:acra:4.10.0'` for the last version of ACRA 4.

**Comment by krupinder955** [comment] 2018-02-17 19:16
Thanks, its working now.
