### ISSUE TITLE
NullPointerException on handleSilentException

### ISSUE THREAD

**Issue by AlexMercier** [ACRA/acra#567] opened 2017-03-29 15:17 UTC
version 4.9.2
I want to send custom error report 
```
ACRA.getErrorReporter().putCustomData("syncBadUrl", url);
ACRA.getErrorReporter().handleSilentException(e);
```
after this my app not crashed, but this report not sended. In logcat I see this: 
```
Failed to send crash reports for /data/data/<MY.PACKAGE.NAME>/app_ACRA-approved/2017-03-29T15:12:34.979+0000-IS_SILENT.stacktrace
   java.lang.NullPointerException
       at org.acra.sender.HttpSender.remap(HttpSender.java:254)
       at org.acra.sender.HttpSender.send(HttpSender.java:221)
       at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:107)
       at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:74)
       at org.acra.sender.SenderService.onHandleIntent(SenderService.java:74)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:137)
       at android.os.HandlerThread.run(HandlerThread.java:60)
```

this is my configuration
```
ConfigurationBuilder c = new ConfigurationBuilder(this)
                .setBuildConfigClass(BuildConfig.class)
                .setFormUri(crashReportUrl)
                .setReportingInteractionMode(ReportingInteractionMode.DIALOG)
                .setResDialogText(R.string.crash_dialog_text)
                .setResDialogTitle(R.string.crash_dialog_title)
                .setResDialogOkToast(R.string.crash_dialog_sendok)
                .setResDialogTheme(R.style.MaterialBaseTheme_Light_AlertDialog)
                .setExcludeMatchingSettingsKeys("SETTINGS_SYSTEM", "SETTINGS_SECURE", "DEVICE_FEATURES", "DUMPSYS_MEMINFO")
                .setExcludeMatchingSharedPreferencesKeys("VK_SDK_ACCESS_TOKEN_PLEASE_DONT_TOUCH", "token");
```

**Comment by F43nd1r** [comment] 2017-04-03 19:48
Duplicate of #541 - closing

**Closed by F43nd1r** 2017-04-03 19:48 UTC
Labels: duplicate
