### ISSUE TITLE
org.acra.config.LimiterConfiguration is no registered configuration w/valid (?) config

### ISSUE THREAD

**Issue by mikehardy** [ACRA/acra#706] opened 2018-10-04 03:14 UTC
With my previous issue(s) I felt like I had something concrete, but I want to be clear that this time I have no idea what's going on, it may be nothing, and if you don't notice something quickly you might let it go - I'll re-open with more details if it reoccurs rather than waste time, but maybe this something you've seen before.

AnkiDroid released a new alpha (2.9alpha38) this morning. We have only integrated the Limiter recently (2 weeks, 6 alpha builds). I have a test in our harness for it and it appears to work fine in testing (including in Travis - it runs a lot...), and for the first 4 official alpha builds with Limiter integrated. This time though, multiple devices had total App start fails.

Our config: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/main/java/com/ichi2/anki/AnkiDroidApp.java#L126

My test: https://github.com/ankidroid/Anki-Android/blob/master/AnkiDroid/src/androidTest/java/com.ichi2.anki.tests/ACRATest.java#L145

Every time you build an app that's published via google play, they throw a robot army at it in their Firebase cloud (for free, with a variety of device specs, actually a neat service), and they record the sessions logcat and video.

On this 5th alpha this morning with AcraLimiter configured, 4 of the 9 test runs they did blew up with the attached stack trace. All the same, but never seen before.

We did another alpha tonight, and everything was fine.  ??

Caused by: java.lang.IllegalArgumentException: org.acra.config.LimiterConfiguration is no registered configuration
	at org.acra.config.ConfigUtils.getPluginConfiguration(ConfigUtils.java:37)
	at org.acra.plugins.HasConfigPlugin.enabled(HasConfigPlugin.java:37)
	at org.acra.plugins.ServicePluginLoader.lambda$loadEnabled$1(ServicePluginLoader.java:43)
	at org.acra.plugins.-$$Lambda$ServicePluginLoader$u1jeZN-wdQcorp41UQTCCyLlscc.apply(Unknown Source:4)
	at org.acra.plugins.ServicePluginLoader.loadInternal(ServicePluginLoader.java:52)
	at org.acra.plugins.ServicePluginLoader.loadEnabled(ServicePluginLoader.java:43)
	at org.acra.builder.ReportExecutor.<init>(ReportExecutor.java:84)
	at org.acra.reporter.ErrorReporterImpl.<init>(ErrorReporterImpl.java:89)
	at org.acra.ACRA.init(ACRA.java:228)
	at org.acra.ACRA.init(ACRA.java:158)
	at org.acra.ACRA.init(ACRA.java:142)
	at com.ichi2.anki.AnkiDroidApp.setAcraConfigBuilder(AnkiDroidApp.java:182)
	at com.ichi2.anki.AnkiDroidApp.setAcraReportingMode(AnkiDroidApp.java:382)
	at com.ichi2.anki.AnkiDroidApp.setProductionACRAConfig(AnkiDroidApp.java:356)
	at com.ichi2.anki.AnkiDroidApp.onCreate(AnkiDroidApp.java:204)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)

I have no solid ideas here. I have a hunch it could be that we converted to androidx and use jetifier, and maybe the toolchain did something wrong for just this build? Maybe they configured all the robots with no background services/activities or some other strange device config that blew this up?

I have full device logcats if helpful.

This was present in the logcat immediately above the exception:

10-03 05:12:24.011: W/ACRA(11408): Couldn't find ConfigurationBuilde
r ToastConfigurationBuilder. ALL CALLS TO IT WILL BE IGNORED!
10-03 05:12:24.012: I/ACRA(11408): Migrating unsent ACRA reports to new file locations
10-03 05:12:24.013: I/ACRA(11408): Migrated 0 unsent reports
10-03 05:12:24.013: I/ACRA(11408): Converting unsent ACRA reports to json
10-03 05:12:24.013: I/ACRA(11408): Converted 0 unsent reports
10-03 05:12:24.014: I/ACRA(11408): ACRA is enabled for com.ichi2.anki, initializing...

Failed app starts were 2x on Android 8.0, 2x on Android 9, all either Portuguese, Spanish or Japonese system language though shouldn't matter - they've run fine before. Other API levels were fine.

**Comment by F43nd1r** [comment] 2018-10-04 13:09
Some info and thoughts on this:
- I am aware of the issue: duplicate of #684 
- It has something to do with `ServiceLoader` and/or the META-INF files it uses to discover services.
- I am planning to deprecate the `PluginLoader` which uses `ServiceLoader` eventually, but haven't found any better replacement. (But the API is already there, and there is one alternative plugin loader `SimplePluginLoader`, which requires to be initialized with a list of all plugins. Which is obviously no viable replacement for `ServiceLoader` discovery)
- I've never been able to reproduce the issue and will close this issue with a new build being apparently the only solution to this

**Closed by F43nd1r** 2018-10-04 13:09 UTC

**Comment by mikehardy** [comment] 2018-10-04 16:51
Interesting - thanks for the info. Is this to say we might be able to compare META-INF files and see a difference? Because we have the APKs available. For us, our ACRA config only changes at very specific times (when integrating, or upgrading ACRA) and after that it is purely static, so if a different less-dynamic configuration style was required (or even available) that made this impossible that would be fine by us - just as a note of user preference. Thanks

**Comment by F43nd1r** [comment] 2018-10-04 17:08
I'd like to see the two apks, could you send them to me? Thanks in advance

**Comment by timrae** [comment] 2018-10-04 20:32
Yeah those releases were seriously broken somehow, I couldn't open them on my device at all. After I did a clean build the problem seemed to go away, so I don't think it's necessary to waste your time looking into this issue... Acra shouldn't be expected to handle malformed releases.

**Comment by mikehardy** [comment] 2018-10-04 21:00
@timrae possibly mystery solved then - @F43nd1r maybe where ever the code that logs config errors (org.acra.config.ConfigUtils.getPluginConfiguration(ConfigUtils.java:37)) could emit a "likely malformed build" type error as it seems this and the issue it duplicated were both acra library user problems and it would throw doubt in the right place to start. Regardless, thanks for the help
