### ISSUE TITLE
reportType = HttpSender.Type.JSON send empty

### ISSUE THREAD

**Issue by changjiashuai** [ACRA/acra#291] opened 2015-07-09 06:35 UTC
reportType = HttpSender.Type.JSON send empty and app crash.

**Comment by william-ferguson-au** [comment] 2015-07-09 20:11
This is not a bug report. It is missing your ACRA config and a stacktrace. I'm closing this issue now.
Feel free to re-open it if you attach your config and a stacktrace.

**Closed by william-ferguson-au** 2015-07-09 20:11 UTC
