### ISSUE TITLE
Parcelable encounteredClassNotFoundException reading a Serializable object (name = org.acra.config.ACRAConfiguration)

### ISSUE THREAD

**Issue by jorgeonpublico** [ACRA/acra#361] opened 2016-02-04 08:17 UTC
In last version:
android.os.Parcel.readSerializable (Parcel.java:2177)
android.content.Intent.getBooleanExtra (Intent.java:4827)
**org.acra.sender.SenderService.onHandleIntent (SenderService.java:33)**
android.app.IntentService$ServiceHandler.handleMessage (IntentService.java:65)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by jorgeonpublico** [comment] 2016-02-04 09:38
also got this:
Fatal Exception: java.lang.ClassCastException
java.lang.Object[] cannot be cast to java.lang.Class[]
 at org.acra.sender.SenderService.onHandleIntent(SenderService.java:37)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:193)
       at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by immobilia** [comment] 2016-02-04 14:18
I confirm this same problem on Android 4.x not on 5.x
This chrash appear only once when i upgrade my old application (with ACRA v4.7) to the new (with ACRA v4.8)

Stack Trace : 

java.lang.RuntimeException: Parcelable encounteredClassNotFoundException reading a Serializable object (name = org.acra.config.ACRAConfiguration)
	at android.os.Parcel.readSerializable(Parcel.java:2148)
	at android.os.Parcel.readValue(Parcel.java:2016)
	at android.os.Parcel.readMapInternal(Parcel.java:2226)
	at android.os.Bundle.unparcel(Bundle.java:223)
	at android.os.Bundle.getBoolean(Bundle.java:802)
	at android.content.Intent.getBooleanExtra(Intent.java:4369)
	at org.acra.sender.SenderService.onHandleIntent(SenderService.java:33)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:153)
	at android.os.HandlerThread.run(HandlerThread.java:60)
Caused by: java.lang.ClassNotFoundException: org.acra.annotation.ReportsCrashes
	at java.lang.Class.classForName(Native Method)
	at java.lang.Class.forName(Class.java:217)
	at java.io.ObjectInputStream.resolveProxyClass(ObjectInputStream.java:1769)
	at java.io.ObjectInputStream.readNewProxyClassDesc(ObjectInputStream.java:1709)
	at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:685)
	at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1806)
	at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2006)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1963)
	at java.io.ObjectInputStream.readFieldValues(ObjectInputStream.java:1140)
	at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:455)
	at java.io.ObjectInputStream.readObjectForClass(ObjectInputStream.java:1372)
	at java.io.ObjectInputStream.readHierarchy(ObjectInputStream.java:1269)
	at java.io.ObjectInputStream.readNewObject(ObjectInputStream.java:1858)
	at java.io.ObjectInputStream.readNonPrimitiveContent(ObjectInputStream.java:787)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:2006)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:1963)
	at android.os.Parcel.readSerializable(Parcel.java:2142)
	... 10 more
Caused by: java.lang.NoClassDefFoundError: org/acra/annotation/ReportsCrashes
	... 28 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.acra.annotation.ReportsCrashes" on path: DexPathList[dexElements=[directory "."],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:53)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:501)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:461)
	... 28 more

**Comment by william-ferguson-au** [comment] 2016-02-04 21:53
This has already been fixed in ACRA-4.8.1
See https://github.com/ACRA/acra/issues/354
And https://github.com/ACRA/acra/wiki/ChangeLog

**Closed by william-ferguson-au** 2016-02-04 21:53 UTC
