### ISSUE TITLE
Empty fields: USER_APP_START_DATE & USER_CRASH_DATE

### ISSUE THREAD

**Issue by DenisZhadan** [ACRA/acra#550] opened 2017-02-16 17:16 UTC
I got log data with empty fields: USER_APP_START_DATE & USER_CRASH_DATE.
Is it Sony phone problem?

```
 [RADIOLOG] =>
     [LOGCAT] =>
     [APP_VERSION_CODE] => 118
     [DEVICE_FEATURES] =>
     [USER_CRASH_DATE] =>
     [AVAILABLE_MEM_SIZE] => 8192
     [BRAND] => Sony
     [INSTALLATION_ID] =>
     [SHARED_PREFERENCES] =>
     [FILE_PATH] => /data/data/eu.sparksoft.liiklustestid/files
     [STACK_TRACE] => java.lang.NullPointerException: Attempt to invoke virtual method 'void android.widget.ArrayAdapter.notifyDataSetChanged()' on a null object reference
         at eu.sparksoft.liiklustestid.question.QuestionActivity.updateStatus(QuestionActivity.java:307)
         at eu.sparksoft.liiklustestid.question.QuestionActivity.access$1100(QuestionActivity.java:54)
         at eu.sparksoft.liiklustestid.question.QuestionActivity$AnswerTask.onPostExecute(QuestionActivity.java:545)
         at eu.sparksoft.liiklustestid.question.QuestionActivity$AnswerTask.onPostExecute(QuestionActivity.java:485)
         at android.os.AsyncTask.finish(AsyncTask.java:632)
         at android.os.AsyncTask.access$600(AsyncTask.java:177)
         at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:645)
         at android.os.Handler.dispatchMessage(Handler.java:102)
         at android.os.Looper.loop(Looper.java:135)
         at android.app.ActivityThread.main(ActivityThread.java:5319)
         at java.lang.reflect.Method.invoke(Native Method)
         at java.lang.reflect.Method.invoke(Method.java:372)
         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1016)
         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:811)

     [PHONE_MODEL] => E2333
     [STACK_TRACE_HASH] => f68239d6
     [TOTAL_MEM_SIZE] => 11887894528
     [EVENTSLOG] =>
     [USER_COMMENT] =>
     [PACKAGE_NAME] => eu.sparksoft.liiklustestid
     [IS_SILENT] =>
     [USER_IP] =>
     [DUMPSYS_MEMINFO] =>
     [APPLICATION_LOG] =>
     [INITIAL_CONFIGURATION] => locale=ru_RU
 compatScreenHeightDp=504
 compatScreenWidthDp=320
 compatSmallestScreenWidthDp=320
 densityDpi=320
 fontScale=1.15
 hardKeyboardHidden=HARDKEYBOARDHIDDEN_YES
 keyboard=KEYBOARD_NOKEYS
 keyboardHidden=KEYBOARDHIDDEN_NO
 mcc=248
 mnc=1
 navigation=NAVIGATION_NONAV
 navigationHidden=NAVIGATIONHIDDEN_YES
 orientation=ORIENTATION_PORTRAIT
 screenHeightDp=567
 screenLayout=SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR
 screenWidthDp=360
 seq=7
 skinPackageSeq=1
 smallestScreenWidthDp=360
 touchscreen=TOUCHSCREEN_FINGER
 uiMode=UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO
 userSetLocale=true

     [BUILD_CONFIG] => APPLICATION_ID=eu.sparksoft.liiklustestid
 BUILD_TYPE=release
 FLAVOR=
 VERSION_NAME=1.1.8 (897)
 DEBUG=false
 VERSION_CODE=118

     [MEDIA_CODEC_LIST] =>
     [THREAD_DETAILS] =>
     [PRODUCT] => E2333
     [DISPLAY] => 0.currentSizeRange.smallest=[720,670]
 0.currentSizeRange.largest=[1196,1134]
 0.flags=FLAG_SUPPORTS_PROTECTED_BUFFERS+FLAG_SECURE
 0.height=1184
 0.metrics.density=2.0
 0.met
     [REPORT_ID] => 4218df14-6df6-4102-83b1-0f5aedead7b5
     [APP_VERSION_NAME] => 1.1.8 (897)
     [SETTINGS_GLOBAL] =>
     [CRASH_CONFIGURATION] => locale=ru_RU
 compatScreenHeightDp=504
 compatScreenWidthDp=320
 compatSmallestScreenWidthDp=320
 densityDpi=320
 fontScale=1.15
 hardKeyboardHidden=HARDKEYBOARDHIDDEN_YES
 keyboard=KEYBOARD_NOKEYS
 keyboardHidden=KEYBOARDHIDDEN_NO
 mcc=248
 mnc=1
 navigation=NAVIGATION_NONAV
 navigationHidden=NAVIGATIONHIDDEN_YES
 orientation=ORIENTATION_PORTRAIT
 screenHeightDp=567
 screenLayout=SCREENLAYOUT_SIZE_NORMAL+SCREENLAYOUT_LONG_NO+SCREENLAYOUT_LAYOUTDIR_LTR
 screenWidthDp=360
 seq=7
 skinPackageSeq=1
 smallestScreenWidthDp=360
 touchscreen=TOUCHSCREEN_FINGER
 uiMode=UI_MODE_TYPE_NORMAL+UI_MODE_NIGHT_NO
 userSetLocale=true

     [SETTINGS_SECURE] =>
     [BUILD] => BOARD=msm8916
 BOOTLOADER=s1
 BRAND=Sony
 CPU_ABI=arm64-v8a
 CPU_ABI2=
 DEVICE=E2333
 DISPLAY=26.1.B.3.109
 FINGERPRINT=Sony/E2333/E2333:5.0/26.1.B.3.109/3057715782:user/release-keys
 HARDWARE=qcom
 HOST=cnbjlx20331
 ID=26.1.B.3.109
 MANUFACTURER=Sony
 MODEL=E2333
 PRODUCT=E2333
 RADIO=unknown
 SERIAL=YT9114A4VL
 SUPPORTED_32_BIT_ABIS=[armeabi-v7a, armeabi]
 SUPPORTED_64_BIT_ABIS=[arm64-v8a]
 SUPPORTED_ABIS=[arm64-v8a, armeabi-v7a, armeabi]
 TAGS=release-keys
 TYPE=user
 UNKNOWN=unknown
 USER=hudsonslave
 IS_DEBUGGABLE=false
 TIME=1456217138000
 VERSION.ACTIVE_CODENAMES=[]
 VERSION.BASE_OS=
 VERSION.CODENAME=REL
 VERSION.INCREMENTAL=3057715782
 VERSION.RELEASE=5.0
 VERSION.SDK=21
 VERSION.SECURITY_PATCH=2015-11-01
 VERSION.RESOURCES_SDK_INT=21
 VERSION.SDK_INT=21

     [ENVIRONMENT] =>
     [ANDROID_VERSION] => 5.0
     [USER_EMAIL] =>
     [SETTINGS_SYSTEM] =>
     [USER_APP_START_DATE] =>
```

**Comment by F43nd1r** [comment] 2017-02-22 14:24
Could not reproduce. Is this reproducible for you? Is it limited to one phone model?

**Comment by F43nd1r** [comment] 2017-09-23 22:50
No followup - closing

**Closed by F43nd1r** 2017-09-23 22:50 UTC
