### ISSUE TITLE
ACRA ignores sharedPreferences concerning acra

### ISSUE THREAD

**Issue by LittleHuba** [ACRA/acra#236] opened 2015-02-11 00:01 UTC
ACRA 4.6.0RC2 ignores acra.enable, acra.disable, acra.syslog.enable, acra.user.email in the shared preferences. It copies them into the report but the have no inflouence on the behaviour of ACRA.

-With acra.enable or acra.disable set with either values ACRA will simply disable all reports
-It will send the syslog everytime, completely ignoring acra.syslog.enable
-The mail of the user is shown in the shared preferences but is not copied into the corresponding fields of the report

**Comment by william-ferguson-au** [comment] 2015-02-11 00:37
Post your ACRA config

**Comment by william-ferguson-au** [comment] 2015-02-11 08:24
I can't reproduce this.

if `acra.disable` is not defined, then ti is determined by `acra.enable`. If that is not defined, then the default is ACRA is enabled.

if 'acra.disable' is defined then it determines whether ACRA is disabled.

**Comment by LittleHuba** [comment] 2015-02-11 11:27
Config:
@ReportsCrashes(
        httpMethod = HttpSender.Method.PUT,
        reportType = HttpSender.Type.JSON,
        formUri = "https://couchdb.huberulrich.de/acra-ffshelf/_design/acra-storage/_update/report",
        formUriBasicAuthLogin = "XXXXXXXXXX",
        formUriBasicAuthPassword = "XXXXXXXXXX",
        mode = ReportingInteractionMode.DIALOG,
        resToastText = R.string.crash_toast_text,
        resDialogText = R.string.crash_dialog_text,
        resDialogIcon = android.R.drawable.ic_dialog_info,
        resDialogTitle = R.string.crash_dialog_title,
        resDialogCommentPrompt = R.string.crash_dialog_comment_prompt
        resDialogOkToast = R.string.crash_dialog_ok_toast
)

I currently deactivated the possibility to stop acra from collecting since I want to make it mandatory.

For the other settings in the report:

![temp1](https://cloud.githubusercontent.com/assets/10881589/6146052/e55fe2e8-b1e8-11e4-9729-101be29843dc.png)

But the mail field is still not set:
![temp1](https://cloud.githubusercontent.com/assets/10881589/6146070/08c22016-b1e9-11e4-8088-42bdd7c6b246.png)

Also the syslogs are still collected and sent with the report. I honestly don't know whats up there.

**Comment by william-ferguson-au** [comment] 2015-02-11 11:48
Are you entering an email address or comment in the crash report dialog?
It doesn't look like you are.

And I don't think you can make collecting crash reports mandatory if you are using mode=dialog, because the user can just cancel the dialog. If you always want to report then use mode=Silent or mode=Toast.

**Comment by LittleHuba** [comment] 2015-02-11 11:56
In the posted report I have not entered a comment. But the commenting of reports works without any problems (Just tested it ;) ).
As far as I know, the mail should be set by the shared preference acra.user.email, which is set. Still ACRA won't take this preference and copy it into the corresponding fields of the report.

Probably I should be more clear. To say it in the easiest way: I want to make it as near to the standard android experience as possible. Which means ACRA is collecting and when the app crashes it asks the user to send the report. What I do not want is that users can completely disable acra. (If the don't want to make the app better they should at least have to cancel the dialog everytime it crashes ;) )

**Comment by william-ferguson-au** [comment] 2015-02-11 12:43
`As far as I know, the mail should be set by the shared preference acra.user.email,`

This is not correct.

The user email address is the oneentered by them into the crash report dialog.
If they provide a value then it is saved to `acra.user.email` and that value will be the default email address the next time the crash dialog is displayed.

**Comment by LittleHuba** [comment] 2015-02-11 12:56
Then please edit your wiki. This is definitely confusing!

Also if the email is entered in the dialog? Where should they enter it?
![device-2015-02-11-135053](https://cloud.githubusercontent.com/assets/10881589/6147196/1d7971e2-b1f5-11e4-831e-8a73a8cca2f5.png)

I only got a field for comments but nothing else?

I highly recommend to rewrite your wiki, since it seems not to be in sync with the actual state of the project. This whole chapter is completely wrong since I set my project up while reading it. https://github.com/ACRA/acra/wiki/AdvancedUsage#letting-your-users-control-acra

I assume I have to change the values programmatically by creating a onPreferenceChangedListener and editing the acraConfig if the corresponding preferences are changed?

**Comment by william-ferguson-au** [comment] 2015-02-11 13:01
That is what I followed this afternoon when I tested the behaviour of acra.enable/acra.disable.
What do you believe is incorrect?

It clearly shows you how to add those preferences into your PreferenceScreen and let the user change them. You don't need to change them programatically.

**Comment by LittleHuba** [comment] 2015-02-11 13:10
Here is part of my preferences.xml:

<PreferenceCategory
        android:key="pref_misc"
        android:title="@string/pref_misc" >
        <PreferenceScreen
            xmlns:android="http://schemas.android.com/apk/res/android"
            android:title="ACRA"
            android:summary="System for bug report"
            android:key="acraScreen">
            <com.lh.ffshelf.misc.ToolbarPreference
                android:key="acraScreen"
                android:title="@string/settings" />
            <SwitchPreference android:key="acra.syslog.enable"
                android:summaryOn="@string/pref_acra_syslog_enabled"
                android:summaryOff="@string/pref_acra_syslog_disabled"
                android:title="@string/pref_acra_syslog"
                android:defaultValue="true"/>
            <EditTextPreference android:key="acra.user.email"
                android:title="@string/pref_acra_user_email"
                android:summary="@string/pref_acra_user_email_summary"/>
        </PreferenceScreen>
    </PreferenceCategory>

Changing those settings is not changing anything in the behaviour of ACRA. I do not know why that is the case but the are completely ignored. I exchanged the checkboxPreferences with SwitchPreferences which should make no problems since the values are still the same (Boolean).

**Comment by william-ferguson-au** [comment] 2015-02-11 13:22
So, do you get or not get sys logs?
What log do you get during crash? It will say one way or the other whether ACRA will give read logs.

It determines whether it can based upon:
`            if (prefs.getBoolean(ACRA.PREF_ENABLE_SYSTEM_LOGS, true)
                && (pm.hasPermission(Manifest.permission.READ_LOGS))
                || Compatibility.getAPILevel() >= 16) {
`

As to the user email as I said before ti is determined based upon what the user enters into the dialog. The real question is why you don't appear to be getting the email field in your crash dialog.

**Comment by LittleHuba** [comment] 2015-02-11 13:29
I do get sys logs. ACRA is collecting them and sending them with the report. But I cannot disable sys logs. 

It seems like ACRA isn't reading the defaultSharedPreferences but others.

That is an interesting question. I'm referencing ACRA via gradle so I haven't changed anything in the sources.

**Comment by william-ferguson-au** [comment] 2015-02-11 13:49
So, if you uncheck the preference for acra.syslog.enable and generate an exception, you get a crash report that contains sys logs?

Have you tried using a CheckboxPreference instead of SwitchPreference?

**Comment by LittleHuba** [comment] 2015-02-11 13:54
Yes that is exactly the case.

I already tried using CheckboxPreference but the result is still the same.

**Comment by LittleHuba** [comment] 2015-02-11 14:00
What I also found and what is quite curious:

![temp1](https://cloud.githubusercontent.com/assets/10881589/6148093/90ed6a4e-b1fe-11e4-8fe3-d079a6ddd6fb.png)

See the one preference in the very first line. A preference without a name makes no real sense. Probably thats the problem.

**Comment by william-ferguson-au** [comment] 2015-02-11 14:05
Possibly, but I couldn't comment about how you have generated that. I can't even see the full preferences.

**Comment by william-ferguson-au** [comment] 2015-02-11 14:20
I suggest you put together a small project that demos the issue and post a link to it, so I can inspect.

**Comment by LittleHuba** [comment] 2015-02-11 14:22
I'm currently checking if there exists another preference file for my app. I'm still unable to get it working. First problem was that ACRA somehow didn't recognize my default settings file and created it's own named "default". I rectified this by explicitely stating my own preference file. But it still ignores the settings.

I'll create a project an upload it to github.

**Comment by LittleHuba** [comment] 2015-02-11 15:38
Here is the link to the project. It's my first project on GitHub so bear with me if something is not working.
This project is not the simplest possible but it's representing the structure of my current app in development. The problems are still the same. (can't deactivate syslog, dialog is not showing field for email)

You can set the values in the settings fragment. the about fragment is for triggering an exception. I'm developing on Android 5.0.x. This might be related to this problem, so keep this in mind if the error isn't occuring on your device.

https://github.com/LittleHuba/ACRATest

Hopefully you're able to fix this.

**Comment by william-ferguson-au** [comment] 2015-02-11 21:56
Can you please cut it down to a minimum project.
Only what is required in order to reproduce the problem.

And make it 100% clear how you are generating the uncaught exception. Explicitly throwing a runtime exception from a button press is the best option.

**Comment by LittleHuba** [comment] 2015-02-12 02:13
The project was tailored down to the absolute minimum. All the errors described above are still there.

**Comment by william-ferguson-au** [comment] 2015-02-12 02:32
It looks like you have 3 or four sub modules.
it is not clear to me which are relevant, or why they are relevant.
It is also not clear how you are forcing the uncaught exception to occur.
It doesn't seem to be using a standard build structure.
And there are build artifacts checked in.

All of that makes it less than clear how I should pick up your project,
build it and attempt to verify any failure and then rectify.
Help me, help you.
ᐧ

**Comment by LittleHuba** [comment] 2015-02-12 12:26
I uploaded a Android Studio Project so I assume you can also pull it with android studio.

It seems like you still have the old project. Please delete it and pull the new version. There should be only one module. When I'm fetching it, it gives me a dialog to delete a vcs root. Please discard this dialog. After that everything should be good to go.

The project consists of one module ('app') with one activity, which has one button, which throws an exception when clicked.

**Comment by LittleHuba** [comment] 2015-02-23 17:46
Any progress?

**Comment by william-ferguson-au** [comment] 2015-02-23 22:40
No. Maybe later this week.
ᐧ

**Comment by william-ferguson-au** [comment] 2015-02-24 14:01
OK 3 problems.

First is that you have configured `sharedPreferencesName = "com.lh.acratest_preferences"` but in your code you are populating `settings = PreferenceManager.getDefaultSharedPreferences(this);` ie the *default* SharedPreferences. Remove that section of your ACRA config and ACRA will read the user email that you are populating.

Second is that after closing the dialog, ACRA rewrites the CrashReport and takes an empty userEmail from the dialog. I will look into why that is.

Third is that the test for adding system logs is improperly formed, so that on a device of API 16 or greater it will always collect logs. I will fix that.

**Closed** 2015-02-24 14:45 UTC

**Comment by LittleHuba** [comment] 2015-02-24 15:17
Thanks a lot! Trying it now.

**Comment by LittleHuba** [comment] 2015-02-24 18:27
Everything seems to be working now. Thanks a lot.

**Comment by william-ferguson-au** [comment] 2015-02-24 22:11
Excellent
ᐧ
