### ISSUE TITLE
Offline Crash not sent when online

### ISSUE THREAD

**Issue by bdndreams** [ACRA/acra#778] opened 2020-05-06 09:59 UTC
Hello 

I have got the crash on offline mode, but when I turn on the WI-FI still report not sent to the server.
It only sent the message when I start the application again.

Please suggest how I can send the report automatically, without depending on the application restart.

**Comment by F43nd1r** [comment] 2020-05-06 12:00
I answered a [very similar question](https://stackoverflow.com/a/61559702/4388512) a few day ago, the answer should help you as well.

**Comment by bdndreams** [comment] 2020-05-06 14:10
Thanks @F43nd1r, I use that AcraScheduler but still facing the issue, might be JobScheduler will take some time to trigger, that I don't know.

Also, some times I got the GET request instead of POST.
Below is my configuration:

> val builder = CoreConfigurationBuilder(context)
                .setBuildConfigClass(BuildConfig::class.java)
                .setReportFormat(StringFormat.JSON)
        builder.setReportContent(ReportField.REPORT_ID, ReportField.STACK_TRACE
            ReportField.CUSTOM_DATA,ReportField.ANDROID_VERSION, ReportField.APP_VERSION_NAME,
            ReportField.APP_VERSION_CODE, ReportField.ANDROID_SDK_VERSION,ReportField.PHONE_MODEL,
            ReportField.INSTALLATION_ID)
        builder.getPluginConfigurationBuilder(HttpSenderConfigurationBuilder::class.java)
                .setUri(url)
                .setHttpMethod(HttpSender.Method.POST)
                .setEnabled(true)
        builder.getPluginConfigurationBuilder(SchedulerConfigurationBuilder::class.java)
                .setRequiresNetworkType(JobInfo.NETWORK_TYPE_UNMETERED)
                .setRequiresBatteryNotLow(true)
                .setEnabled(true)

**Comment by F43nd1r** [comment] 2020-05-06 16:08
Are you using version 5.5.1? If not, please do so, there was a bug in the scheduler.

**Comment by bdndreams** [comment] 2020-05-07 05:52
Yes, I am using version 5.5.1. Is this fixed available in this latest code?

**Comment by F43nd1r** [comment] 2020-05-07 13:37
Fix was released in 5.5.1, so this must be something different.

**Comment by F43nd1r** [comment] 2020-05-11 12:39
I was unable to reproduce this. What are the circumstances? (device, android version, ...)

**Comment by bdndreams** [comment] 2020-05-15 12:00
Hello @F43nd1r,  I have added your last commit for [40ab1a7](https://github.com/ACRA/acra/commit/40ab1a7e7e5ff97b2b98380dbd6e8356736f97f9), then after I have not faced this issue.

**Closed** 2020-05-15 12:01 UTC
Labels: bug
