### ISSUE TITLE
NPE at org.acra.ErrorReporter.endApplication(ErrorReporter.java:396

### ISSUE THREAD

**Issue by ezraroi** [ACRA/acra#119] opened 2013-11-09 22:30 UTC
Hi, i am using the latest version of ACRA and i am getting NPE. The line that calls "ACRA.getErrorReporter().handleException(error, true);" is throwing NPE.
Here is my complete code:

@Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
            logger.info("onCreateView()");
	    View view = inflater.inflate(R.layout.splash,  container, false);
	    LoginButton authButton = (LoginButton) view.findViewById(R.id.login_button);
	    //authButton.setReadPermissions(Arrays.asList("basic_info","user_photos", "friends_relationships", "friends_photos"));
	    authButton.setReadPermissions(Arrays.asList("user_photos", "friends_relationships", "friends_photos"));
	    authButton.setOnErrorListener(new OnErrorListener() {

			@Override
			public void onError(FacebookException error) {
				logger.error("Facebook login error", error);
				Toast.makeText(getActivity(), R.string.facebook_connection_problem, Toast.LENGTH_LONG).show();
				ACRA.getErrorReporter().handleException(error, true);
			}
	    	
	    });
	    return view;
	}

**Comment by andrewthecoder** [comment] 2015-01-14 09:46
I was getting this NPE occasionally with my usage of 4.5.0 (which makes the log quite useless, as there is no information about the actual crash, even in the logcat), so I just upgraded to 4.6.0RC1 and it still doesn't seem to be fixed, just moved?

Here's my stack trace:

Uncaught exception
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.Throwable.getMessage()' on a null object reference
at org.acra.ErrorReporter.endApplication(ErrorReporter.java:454)
at org.acra.ErrorReporter.access$800(ErrorReporter.java:82)
at org.acra.ErrorReporter$5.run(ErrorReporter.java:818)

**Comment by andrewthecoder** [comment] 2015-01-14 09:57
Actually, given that this is an issue in endApplication, I just changed my functions which were wrapped with

try {
    ...
} catch (Exception e) {
    ACRA.getErrorReporter().handleException(e, true);
}

to use the 
ACRA.getErrorReporter().handleException(e);
exception handling signature.

As this is no longer trying to close my application after a crash, I no longer get this issue and I actually get useful bug reports again!
Any suggestions for what I could try to get ACRA to close my application after a crash, without crashing itself and thus ruining the bug reports?
Thanks a bunch.

**Comment by william-ferguson-au** [comment] 2015-01-14 14:09
@andrewthecoder what ReportingInteractionMode are you using?

It looks like there is a bug in #169 where the app will not be killed if  SILENT || (TOAST && forceCloseDialogAfterToast()

**Comment by andrewthecoder** [comment] 2015-01-14 14:49
Thanks for the quick response!

Dialog. In fact, here's my config:

@ReportsCrashes(
        mode = ReportingInteractionMode.DIALOG,
        resToastText = R.string.crash_toast_text, // optional, displayed as soon as the crash occurs, before collecting data which can take a few seconds
        resDialogText = R.string.crash_dialog_text,
        resDialogIcon = android.R.drawable.ic_dialog_info, //optional. default is a warning sign
        resDialogTitle = R.string.crash_dialog_title, // optional. default is your application name
        resDialogCommentPrompt = R.string.crash_dialog_comment_prompt, // optional. when defined, adds a user text field input with this text resource as a label
        resDialogOkToast = R.string.crash_dialog_ok_toast, // optional. displays a Toast message when the user accepts to send a report.

        customReportContent = {
                ReportField.ANDROID_VERSION,
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ReportField.AVAILABLE_MEM_SIZE,
                ReportField.BRAND,
                ReportField.BUILD,
                ReportField.CRASH_CONFIGURATION,
                ReportField.CUSTOM_DATA,
                ReportField.DEVICE_FEATURES,
                ReportField.DEVICE_ID,
                ReportField.DISPLAY,
                ReportField.ENVIRONMENT,
                ReportField.FILE_PATH,
                ReportField.INITIAL_CONFIGURATION,
                ReportField.INSTALLATION_ID,
                ReportField.IS_SILENT,
                ReportField.LOGCAT,
                ReportField.PACKAGE_NAME,
                ReportField.PHONE_MODEL,
                ReportField.PRODUCT,
                ReportField.REPORT_ID,
                ReportField.SETTINGS_GLOBAL,
                ReportField.SETTINGS_SECURE,
                ReportField.SETTINGS_SYSTEM,
                ReportField.SHARED_PREFERENCES,
                ReportField.STACK_TRACE,
                ReportField.THREAD_DETAILS,
                ReportField.TOTAL_MEM_SIZE,
                ReportField.USER_APP_START_DATE,
                ReportField.USER_COMMENT,
                ReportField.USER_CRASH_DATE,
                ReportField.USER_EMAIL
        },

        formKey = "",
        httpMethod = org.acra.sender.HttpSender.Method.PUT,
        reportType = org.acra.sender.HttpSender.Type.JSON,
        formUri = "http://couch.andrewbeveridge.co.uk/acra-podfather/_design/acra-storage/_update/report",
        formUriBasicAuthLogin = "[OMITTED]",
        formUriBasicAuthPassword = "[OMITTED]"
)

**Comment by william-ferguson-au** [comment] 2015-01-15 02:48
Actually, it looks like the problem is that ```endApplication()``` was only even written to cater for uncaught Exceptions. Testing a fix now.

**Comment by andrewthecoder** [comment] 2015-01-15 11:48
Thanks a bunch! 
Once 4.6.0RC2 is released I'll give it a test.

**Comment by william-ferguson-au** [comment] 2015-01-15 12:40
You can build it from master now.


  [image: photo]
*William Ferguson*
Founder and CEO, XandarMob
 m:+61 425 716 870 | e:william.ferguson@xandar.com.au |
w:https://wylas-timing.com
http://lexathon.com <http://wylas-timing.com http://lexathon.com>
  ᐧ

**Comment by william-ferguson-au** [comment] 2015-01-22 01:26
Fixed in #216

**Closed by william-ferguson-au** 2015-01-22 01:26 UTC
