### ISSUE TITLE
HttpSender.remap crashes while flatten()-ing report field [4.9.2]

### ISSUE THREAD

**Issue by dakics** [ACRA/acra#603] opened 2017-11-03 16:54 UTC
ACRA 4.9.2  / Android 8 / Nexus 5X , but also various emulators/APIs

This line crashes in the HttpSender.remap method:

String value = TextUtils.join("\n", report.get(field).flatten());

```
 java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String[] org.acra.model.Element.flatten()' on a null object reference
at org.acra.sender.HttpSender.remap(HttpSender.java:254)
at org.acra.sender.HttpSender.send(HttpSender.java:221)
at org.acra.sender.ReportDistributor.sendCrashReport(ReportDistributor.java:107)
at org.acra.sender.ReportDistributor.distribute(ReportDistributor.java:74)
at org.acra.sender.SenderService.onHandleIntent(SenderService.java:74)
at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:68)
at android.os.Handler.dispatchMessage(Handler.java:105)
at android.os.Looper.loop(Looper.java:164)
at android.os.HandlerThread.run(HandlerThread.java:65)
```

ACRA 4.9.1 works fine. I see the difference is it outputs report.get(field) value, without calling flatten();

I'm outputting all ReportFields, but was not able to narrow down to the offending field yet.

```
@ReportsCrashes(
        formUri = ACRA_CRASH_REPORT_URI,   // our backend
        mode = ReportingInteractionMode.TOAST,
        resToastText = R.string.crash_toast_text,    // "Oops error"
        reportType = HttpSender.Type.FORM,
        httpMethod = HttpSender.Method.POST,
        logcatArguments = {"-t", "2000", "-v", "long", "BluetoothAdapter:S BluetoothLeScanner:S ScanRecord:S *:V"},
        customReportContent = {
                ReportField.REPORT_ID,
                ReportField.APP_VERSION_CODE,
                ReportField.APP_VERSION_NAME,
                ...
                ReportField.USER_IP
        }

```

**Comment by F43nd1r** [comment] 2017-11-03 17:08
Duplicate of #541

**Closed by F43nd1r** 2017-11-03 17:08 UTC
